# Name of website
title: QNN Write-ups
github: itstorque

# Your name to show in the footer
author: Torque Dandachi

# If you want your website to generate an RSS feed, provide a description
# The URL for the feed will be https://<your_website>/feed.xml
rss-description: A public facing portal of some of the write-ups I produced in my research at MIT's QNN group.

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# jekyll-paginate configuration
paginate: 5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title

usemathjax: true

remote_theme: niklasbuschmann/contrast@v2.11

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      comments: false


# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# excerpt_separator: "\n\n\n"

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}

# mathjax: true
